lzp1_subscription_id             = "__lzp1subscriptionid__"
tenant_id                        = "__tenantid__"
environment                      = "Lab"
owner                            = "storage"
project                          = "Storage"
storage_vault_name               = "__vaultname__"
lotr_storage_account_name        = "__lotrstorageaccountname__"
datafactory_storage_account_name = "__datafactorystorageaccountname__"
