trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure-lab/image-bakery/windows/win2025-core.pkr.hcl  

pool:
  name: 'Lab'  

extends:
  template: templates/template-packer-ci.yml  
  parameters:
    artifactName: "windows-2025-core-artifacts"
    imageName: "windows-2025-core"
    agentPool: "Lab"