lab_subscription_id        = "__labsubscriptionid__"
management_subscription_id = "__managementsubscriptionid__"
tenant_id                  = "__tenantid__"
environment                = "Test"
owner                      = "apps"
project                    = "Applications"