trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure-lab/image-bakery/windows/win2025-base.pkr.hcl  

pool:
  name: 'Lab'  

extends:
  template: templates/template-packer-ci.yml  
  parameters:
    artifactName: "windows-2025-base-artifacts"
    imageName: "windows-2025-base"
    agentPool: "Lab"