lab_subscription_id        = "__labsubscriptionid__"
management_subscription_id = "__managementsubscriptionid__"
tenant_id                  = "__tenantid__"
environment                = "Lab"
owner                      = "networking"
project                    = "Networking"
vault_name                 = "__vaultname__"