lza2_subscription_id = "__lza2subscriptionid__"
tenant_id            = "__tenantid__"
environment          = "Lab"
owner                = "appsingle"
project              = "Applications"
appsingle_vault_name = "__vaultname__"