parameters:
  - name: team
    type: string
  - name: artifactName
    type: string
  - name: environments
    type: object
  - name: variableGroup
    type: string
  - name: backendServiceArm
    type: string  # Optional backend service connection

stages:
  - ${{ each env in parameters.environments }}:
      - stage: Plan${{ env }}
        displayName: 'Terraform Plan - ${{ env }}'
        dependsOn: []
        variables:
          - group: ${{ parameters.variableGroup }}  # Pull secrets from Key Vault
          - name: artifactName
            value: ${{ parameters.artifactName }}
          - name: backendServiceArm
            value: ${{ coalesce(parameters.backendServiceArm, 'Default-Terraform-Service-Connection') }}
        jobs:
          - deployment: Terraform_Plan
            displayName: 'Terraform Init & Plan - ${{ env }}'
            environment: ${{ env }}
            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self

                    # 🔽 **Ensure Terraform is Installed**
                    - task: TerraformInstaller@1
                      displayName: 'Install Terraform'
                      inputs:
                        terraformVersion: "latest"

                    # 🔽 **Terraform Init**
                    - task: TerraformCLI@1
                      displayName: 'Terraform Init - ${{ env }}'
                      inputs:
                        command: "init"
                        backendType: "azurerm"
                        backendServiceArm: "$(backendServiceArm)"
                        backendAzureRmResourceGroupName: "$(backendResourceGroup)"
                        backendAzureRmStorageAccountName: "$(backendStorageAccount)"
                        backendAzureRmContainerName: "$(backendContainer)"
                        backendAzureRmKey: "$(team)/${{ env }}.tfstate"
                      workingDirectory: '$(Pipeline.Workspace)/$(artifactName)/$(team)'

                    # 🔽 **Terraform Validate**
                    - task: TerraformCLI@1
                      displayName: 'Terraform Validate - ${{ env }}'
                      inputs:
                        command: "validate"
                        provider: "azurerm"
                      workingDirectory: '$(Pipeline.Workspace)/$(artifactName)/$(team)'

                    # 🔽 **Terraform Plan**
                    - task: TerraformCLI@1
                      displayName: 'Terraform Plan - ${{ env }}'
                      inputs:
                        command: "plan"
                        provider: "azurerm"
                        commandOptions: "-var environment=${{ env }} -var tenant_id=$(tenantid) -var subscription_id=$(subscriptionid) -refresh=false -out=${{ env }}-tfplan -input=false -no-color -detailed-exitcode"
                      workingDirectory: '$(Pipeline.Workspace)/$(artifactName)/$(team)'