parameters:
  - name: team
    type: string
  - name: artifactName
    type: string
  - name: variableGroup
    type: string
  - name: backendServiceArm
    type: string
  - name: environmentName
    type: string
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: workingDirectory
    type: string
  - name: agentPool
    type: string 

stages:
  - stage: ${{ parameters.stageName }}
    displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
    pool:
      name: ${{ parameters.agentPool }}  # ✅ Uses the passed-in agent pool
    variables:
      - group: ${{ parameters.variableGroup }}  # ✅ Pull secrets from Key Vault
    jobs:
      - deployment: Terraform_Plan
        displayName: 'Terraform Init & Plan - ${{ parameters.stageDisplayName }}'
        environment: ${{ parameters.environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # ✅ Debug Step: Log environment and paths
                - script: |
                    echo "🔍 Debugging Terraform PATH"
                    echo "🔧 Current PATH: $PATH"
                    echo "📦 Installed Terraform Versions:"
                    ls -l /home/azureuser/myagent/_work/_tool/terraform/
                    echo "📌 Terraform Binary Location:"
                    which terraform || echo "⚠️ Terraform binary not found!"
                  displayName: "Debug: Verify Terraform PATH"
                  failOnStderr: false
                  continueOnError: true

                # ✅ Ensure Terraform is installed
                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: "latest"

                # ✅ Manually Update PATH (Fix execution issue)
                - script: |
                    echo "🔄 Updating PATH for Terraform..."
                    export PATH="/home/azureuser/myagent/_work/_tool/terraform/1.11.1/x64:$PATH"
                    echo "✅ PATH Updated: $PATH"
                    terraform version
                  displayName: "Fix: Manually Update Terraform PATH"

                # ✅ Initialize Terraform backend
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Init - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "init"
                    backendType: "azurerm"
                    backendServiceArm: ${{ parameters.backendServiceArm }}
                    backendAzureRmResourceGroupName: "$(backendResourceGroup)"
                    backendAzureRmStorageAccountName: "$(backendStorageAccount)"
                    backendAzureRmContainerName: "$(backendContainer)"
                    backendAzureRmKey: "$(team)/${{ parameters.environmentName }}.tfstate"
                    workingDirectory: ${{ parameters.workingDirectory }}

                # ✅ Validate Terraform configuration
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Validate - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "validate"
                    provider: "azurerm"
                    workingDirectory: ${{ parameters.workingDirectory }}

                # ✅ Run Terraform plan
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "plan"
                    provider: "azurerm"
                    commandOptions: "-var environment=${{ parameters.environmentName }} -var tenant_id=$(tenantid) -var subscription_id=$(subscriptionid) -refresh=false -out=${{ parameters.environmentName }}-tfplan -input=false -no-color -detailed-exitcode"
                    workingDirectory: ${{ parameters.workingDirectory }}