parameters:
  - name: team
    type: string
  - name: artifactName
    type: string
  - name: variableGroup
    type: string
  - name: backendServiceArm
    type: string
  - name: environmentName
    type: string
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: workingDirectory
    type: string
  - name: agentPool
    type: string 
  - name: pipeline
    type: string 

stages:
  - stage: ${{ parameters.stageName }}
    displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
    pool:
      name: ${{ parameters.agentPool }}  # ✅ Uses the passed-in agent pool
    variables:
      - group: ${{ parameters.variableGroup }}  # ✅ Pull secrets from Key Vault
    jobs:
      - deployment: Terraform_Plan
        displayName: 'Terraform Init & Plan - ${{ parameters.stageDisplayName }}'
        environment: ${{ parameters.environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - script: |
                    echo "🔍 Debugging Artifact Variables"
                    echo "Artifact Name: '${{ parameters.artifactName }}'"
                    echo "Pipeline: '${{ parameters.pipeline }}'"
                    echo "Download Path: '$(Pipeline.Workspace)'"
                  displayName: "Debug: Verify Artifact Variables"

                - script: |
                    echo "🔍 Listing contents of $(Pipeline.Workspace)/${{ parameters.artifactName }}/$(team)"
                    ls -la "$(Pipeline.Workspace)/${{ parameters.artifactName }}/$(team)"
                  displayName: "Debug: Verify Downloaded Artifacts"

                # ✅ Ensure Terraform is installed
                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: "latest"

                - script: |
                    echo "🔍 Checking Terraform installation..."
                    ls -la /home/azureuser/myagent/_work/_tool/terraform/
                    ls -la /home/azureuser/myagent/_work/_tool/terraform/1.11.1/x64/
                    which terraform
                    terraform version
                  displayName: "Debug: Verify Terraform Installation"

                - script: |
                    echo "🔍 Checking PATH Variable..."
                    echo $PATH
                  displayName: "Debug: Check PATH Variable"

                - script: |
                    export PATH=$PATH:/home/azureuser/myagent/_work/_tool/terraform/1.11.1/x64/
                    echo "Updated PATH: $PATH"
                  displayName: "Fix: Update PATH Variable"

                - script: |
                    echo "Setting backend variables..."
                    export TF_BACKEND_CONTAINER=$(backendContainer)
                    export TF_BACKEND_STORAGE_ACCOUNT=$(backendStorageAccount)
                    export TF_BACKEND_RESOURCE_GROUP=$(backendResourceGroup)
                  displayName: "Set Backend Variables"

                - script: |
                    if [ -z "$TF_BACKEND_CONTAINER" ] || [ -z "$TF_BACKEND_STORAGE_ACCOUNT" ] || [ -z "$TF_BACKEND_RESOURCE_GROUP" ]; then
                        echo "❌ ERROR: One or more backend variables are missing!"
                        exit 1
                    fi
                  displayName: "Validate Backend Variables"

                # ✅ Initialize Terraform backend
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Init - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "init"
                    backendType: "azurerm"
                    backendServiceArm: ${{ parameters.backendServiceArm }}
                    backendAzureRmResourceGroupName: "$(TF_BACKEND_RESOURCE_GROUP)"
                    backendAzureRmStorageAccountName: "$(TF_BACKEND_STORAGE_ACCOUNT)"
                    backendAzureRmContainerName: "$(TF_BACKEND_CONTAINER)"
                    backendAzureRmKey: "$(team)/${{ parameters.environmentName }}.tfstate"
                    workingDirectory: "$(Pipeline.Workspace)/${{ parameters.artifactName }}/$(team)"

                # ✅ Validate Terraform configuration
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Validate - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "validate"
                    provider: "azurerm"
                    workingDirectory: "$(Pipeline.Workspace)/${{ parameters.artifactName }}/$(team)"

                # ✅ Run Terraform plan
                - task: TerraformTaskV4@4
                  displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "plan"
                    provider: "azurerm"
                    commandOptions: "-var environment=${{ parameters.environmentName }} -var tenant_id=$(tenantid) -var subscription_id=$(subscriptionid) -refresh=false -out=${{ parameters.environmentName }}-tfplan -input=false -no-color -detailed-exitcode"
                    workingDirectory: "$(Pipeline.Workspace)/${{ parameters.artifactName }}/$(team)"