parameters:
  - name: artifactName
    type: string
  - name: team
    type: string
  - name: branchFilter
    type: object
    default: ["main"]
  - name: pathFilter
    type: string
    default: "security/**"
  - name: agentPool
    type: string
    default: "Lab"

trigger:
  branches:
    include: ${{ parameters.branchFilter }}
  paths:
    include:
      - ${{ parameters.pathFilter }}

variables:
  - name: artifactName
    value: ${{ parameters.artifactName }}
  - name: team
    value: ${{ parameters.team }}

stages:
  - stage: Build
    displayName: 'Build Stage'
    pool:
      name: ${{ parameters.agentPool }}  # ✅ Pool is now inside `stages`
    jobs:
      - job: Build
        displayName: 'Prepare Terraform Artifacts'
        steps:
          - checkout: self
            fetchDepth: 1 

          - task: CopyFiles@2
            displayName: 'Copy Terraform Files for ${{ parameters.team }}'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/${{ parameters.team }}'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(artifactName)/${{ parameters.team }}'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Terraform Artifacts'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
              artifactName: '$(artifactName)'