parameters:
  - name: team
    type: string
  - name: artifactName
    type: string
  - name: variableGroup
    type: string
  - name: backendServiceArm
    type: string
  - name: environmentName
    type: string
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: workingDirectory
    type: string
  - name: agentPool
    type: string  # ✅ Now configurable from the calling pipeline

stages:
  - stage: ${{ parameters.stageName }}
    displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
    pool:
      name: ${{ parameters.agentPool }}  # ✅ Uses the passed-in agent pool
    variables:
      - group: ${{ parameters.variableGroup }}  # Pull secrets from Key Vault
    jobs:
      - deployment: Terraform_Plan
        displayName: 'Terraform Init & Plan - ${{ parameters.stageDisplayName }}'
        environment: ${{ parameters.environmentName }}
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: TerraformInstaller@1
                  displayName: 'Install Terraform'
                  inputs:
                    terraformVersion: "latest"

                - task: TerraformCLI@1
                  displayName: 'Terraform Init - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "init"
                    backendType: "azurerm"
                    backendServiceArm: "$(backendServiceArm)"
                    backendAzureRmResourceGroupName: "$(backendResourceGroup)"
                    backendAzureRmStorageAccountName: "$(backendStorageAccount)"
                    backendAzureRmContainerName: "$(backendContainer)"
                    backendAzureRmKey: "$(team)/${{ parameters.environmentName }}.tfstate"
                  workingDirectory: ${{ parameters.workingDirectory }}

                - task: TerraformCLI@1
                  displayName: 'Terraform Validate - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "validate"
                    provider: "azurerm"
                  workingDirectory: ${{ parameters.workingDirectory }}

                - task: TerraformCLI@1
                  displayName: 'Terraform Plan - ${{ parameters.stageDisplayName }}'
                  inputs:
                    command: "plan"
                    provider: "azurerm"
                    commandOptions: "-var environment=${{ parameters.environmentName }} -var tenant_id=$(tenantid) -var subscription_id=$(subscriptionid) -refresh=false -out=${{ parameters.environmentName }}-tfplan -input=false -no-color -detailed-exitcode"
                  workingDirectory: ${{ parameters.workingDirectory }}