parameters:
  - name: artifactName
    type: string
  - name: team
    type: string
  - name: branchFilter
    type: object
    default: ["main"]
  - name: pathFilter
    type: string
    default: "security/**"
  - name: agentPool
    type: string
    default: "Lab"

# 🚀 Name field does NOT support parameters
name: CI-$(Build.SourceBranchName)-$(Build.BuildId)  # Removed parameter reference

trigger:
  branches:
    include:
      - main  # Hardcoded because parameters are not supported here
  paths:
    include:
      - security/**  # Hardcoded for same reason

# 🚀 Pool CANNOT use parameters, so it's set directly
pool:
  name: "Lab"

variables:
  - name: artifactName
    value: ${{ parameters.artifactName }}
  - name: team
    value: ${{ parameters.team }}

stages:
  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Prepare Terraform Artifacts'
        steps:
          - checkout: self
            fetchDepth: 1 

          - task: CopyFiles@2
            displayName: 'Copy $(team) Terraform Files'  # Using variables (allowed)
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)/$(team)'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/$(artifactName)/$(team)'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Terraform Artifacts'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
              artifactName: '$(artifactName)'