trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - apps/appsingle/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-app-ci.yml  
  parameters:
    artifactName: "appsingle-artifacts"
    team: "appsingle"
    agentPool: "Lab"