trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - apps/datahub/main.tf

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-app-ci.yml  
  parameters:
    artifactName: "datahub-artifacts"
    team: "datahub"
    agentPool: "Lab"