trigger: none

resources:
  pipelines:
    - pipeline: AppMulti-CI
      source: AppMulti-CI
      trigger:
        branches:
          - main

pool:
  name: 'Lab'

stages:
  - template: templates/template-terraform-plannew.yml
    parameters:
      team: "appmulti"
      artifactName: "appmulti-artifacts"
      variableGroup: "Application"
      backendServiceArm: "Application-SC"
      environmentName: "dev"
      stageName: "dev"
      stageDisplayName: "Development"
      workingDirectory: "$(Pipeline.Workspace)/AppMulti-CI/appmulti-artifacts/apps/appmulti"
      agentPool: "Lab"
      pipeline: "AppMulti-CI"
      dependsOn: []  # Explicitly set to an empty list for independent execution

  - template: templates/template-terraform-plannew.yml
    parameters:
      team: "appmulti"
      artifactName: "appmulti-artifacts"
      variableGroup: "Application"
      backendServiceArm: "Application-SC"
      environmentName: "test"
      stageName: "test"
      stageDisplayName: "Test Environment"
      workingDirectory: "$(Pipeline.Workspace)/AppMulti-CI/appmulti-artifacts/apps/appmulti"
      agentPool: "Lab"
      pipeline: "AppMulti-CI"
      dependsOn: ["dev"]  # Correctly references the actual stage name

  - template: templates/template-terraform-plannew.yml
    parameters:
      team: "appmulti"
      artifactName: "appmulti-artifacts"
      variableGroup: "Application"
      backendServiceArm: "Application-SC"
      environmentName: "prod"
      stageName: "prod"
      stageDisplayName: "Production Environment"
      workingDirectory: "$(Pipeline.Workspace)/AppMulti-CI/appmulti-artifacts/apps/appmulti"
      agentPool: "Lab"
      pipeline: "AppMulti-CI"
      dependsOn: ["test"]  # Correctly references the actual stage name