trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure-lab/compute/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-ci.yml  
  parameters:
    artifactName: "compute-artifacts"
    team: "compute"
    agentPool: "Lab"