trigger: none

resources:
  pipelines:
    - pipeline: DevOps-CI
      source: DevOps-CI
      trigger:
        branches:
          - main

pool:
  name: 'Lab'

stages:
  - template: templates/template-terraform-cd.yml
    parameters:
      team: "devops"
      artifactName: "devops-artifacts"
      variableGroup: "DevOps"
      backendServiceArm: "DevOps-SC"
      environmentName: "lab"
      stageName: "lab"
      stageDisplayName: "Development"
      workingDirectory: "$(Pipeline.Workspace)/DevOps-CI/devops-artifacts/azure-lab/devops"
      agentPool: "Lab"
      pipeline: "DevOps-CI"
      dependsOn: []  # Explicitly set to an empty list for independent execution