trigger: none

resources:
  pipelines:
    - pipeline: Networking-CI
      source: Networking-CI
      trigger:
        branches:
          - main

pool:
  name: 'Lab'

stages:
  - template: templates/template-terraform-plan.yml
    parameters:
      team: "networking"
      artifactName: "networking-artifacts"
      variableGroup: "Networking"
      backendServiceArm: "Lab-SC"
      environmentName: "lab"
      stageName: "lab"
      stageDisplayName: "Development"
      workingDirectory: "$(Pipeline.Workspace)/Networking-CI/networking-artifacts/azure-lab/networking"
      agentPool: "Lab"
      pipeline: "Networking-CI"