trigger: none  # Runs only when explicitly triggered

resources:
  pipelines:
    - pipeline: Security-CI
      source: Security-CI
      trigger:
        branches:
          - main

pool:
  name: 'Lab'

stages:
  - template: templates/template-terraform-plan.yml
    parameters:
      team: "security"
      artifactName: "security-artifacts"
      variableGroup: "Security"
      backendServiceArm: "Lab-SC"
      environmentName: "lab"
      stageName: "lab"
      stageDisplayName: "Development"
      workingDirectory: "$(Pipeline.Workspace)/security-artifacts/azure-lab/security"
      agentPool: "Lab"
      pipeline: "Security-CI"