trigger:
  branches:
    include:
      - main
  paths:
    include:
      - azure-lab/security/**

pool:
  name: 'Lab'

variables:
  - name: artifactName
    value: "security-artifacts"
  - name: team
    value: "security"

extends:
  template: templates/template-terraform-ci.yml
  parameters:
    artifactName: "security-artifacts"
    team: "security"
    branchFilter: ["main"]
    pathFilter: "azure-lab/security/**"
    agentPool: "Lab"