trigger:
  branches:
    include:
      - main  # Hardcoded branch since parameters are not allowed
  paths:
    include:
      - azure-lab/security/**  # Adjusted for correct directory

pool:
  name: 'Lab'  # Hardcoded since pool cannot use parameters

variables:
  - name: artifactName
    value: "security-artifacts"
  - name: team
    value: "security"

extends:
  template: templates/template-terraform-ci.yml
  parameters:
    artifactName: "security-artifacts"
    team: "security"
    agentPool: "Lab"  # Removed `branchFilter` and `pathFilter` from here