stages:
  - template: templates/template-terraform-plan.yml
    parameters:
      team: "security"
      artifactName: "security-artifacts"
      environments: ["lab"]
      variableGroup: "Security"
      backendServiceArm: "Lab"