trigger:
  branches:
    include:
      - main  # Hardcoded because parameters are not supported in `trigger`
  paths:
    include:
      - security/**  # Hardcoded because parameters are not supported in `paths`

pool:
  name: 'Lab'  # Pool must be hardcoded since parameters don't work here

extends:
  template: pipelines/templates/template-terraform-ci.yml
  parameters:
    artifactName: "security-artifacts"
    team: "security"
    agentPool: "Lab"