trigger:
  branches:
    include:
      - main  # Hardcoded, since parameters/variables cannot be used in `trigger`
  paths:
    include:
      - security/**  # Hardcoded for the same reason

pool:
  name: 'Lab'  # Pool must be hardcoded since parameters/variables don't work here

variables:
  - name: artifactName
    value: "security-artifacts"
  - name: team
    value: "security"

extends:
  template: pipelines/templates/template-terraform-ci.yml
  parameters:
    artifactName: "security-artifacts"
    team: "security"
    branchFilter: ["main"]
    pathFilter: "security/**"
    agentPool: "Lab"