trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - apps/twingate/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-app-ci.yml  
  parameters:
    artifactName: "twingate-artifacts"
    team: "twingate"
    agentPool: "Lab"