parameters:
  - name: imageName
    type: string
  - name: artifactName
    type: string
  - name: variableGroup
    type: string
  - name: backendServiceArm
    type: string
  - name: environmentName
    type: string
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: workingDirectory
    type: string
  - name: agentPool
    type: string
  - name: pipeline
    type: string
  - name: dependsOn
    type: object
    default: []  # Default to an empty list if not provided
  - name: packerTemplateFile
    type: string  # Required parameter, no default value

stages:
  - stage: ${{ parameters.stageName }}
    displayName: "Packer Validate - ${{ parameters.stageDisplayName }}"
    dependsOn: ${{ parameters.dependsOn }}
    pool:
      name: ${{ parameters.agentPool }}

    variables:
      - group: ${{ parameters.variableGroup }}  # Pull secrets from Key Vault

    jobs:
      - deployment: Packer_Validate
        displayName: "Packer Init & Validate - ${{ parameters.stageDisplayName }}"
        environment: validate
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                # ✅ Install Packer (Cross-platform)
                - task: PowerShell@2
                  displayName: "Install Packer (Cross-platform)"
                  inputs:
                    targetType: "inline"
                    script: |
                      $packerInstalled = $false
                      Write-Host "Detecting if Packer is installed..."
                      if ($env:AGENT_OS -eq "Windows_NT") {
                        try {
                          packer -v | Out-Null
                          $packerInstalled = $true
                        } catch {
                          Write-Host "Packer not found on Windows."
                        }

                        if (-not $packerInstalled) {
                          Write-Host "Installing Packer on Windows..."
                          $version = (Invoke-RestMethod -Uri "https://checkpoint-api.hashicorp.com/v1/check/packer").current_version
                          $zipUrl = "https://releases.hashicorp.com/packer/$version/packer_${version}_windows_amd64.zip"
                          $zipPath = "$env:TEMP\packer.zip"
                          $installPath = "C:\HashiCorp\packer"

                          Invoke-WebRequest -Uri $zipUrl -OutFile $zipPath
                          Expand-Archive -Path $zipPath -DestinationPath $installPath -Force
                          $env:PATH += ";$installPath"
                          [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [EnvironmentVariableTarget]::Machine)
                          Write-Host "Packer installed at $installPath"
                        }
                        else {
                          Write-Host "Packer already installed on Windows."
                        }
                      }
                      else {
                        try {
                          bash -c "packer -v" | Out-Null
                          $packerInstalled = $true
                        } catch {
                          Write-Host "Packer not found on Linux/macOS."
                        }

                        if (-not $packerInstalled) {
                          Write-Host "Installing Packer on Linux/macOS..."
                          $version = (Invoke-RestMethod -Uri "https://checkpoint-api.hashicorp.com/v1/check/packer").current_version
                          $zipUrl = "https://releases.hashicorp.com/packer/$version/packer_${version}_linux_amd64.zip"
                          $zipPath = "./packer.zip"

                          curl -fsSL $zipUrl -o $zipPath
                          unzip $zipPath
                          sudo mv packer /usr/local/bin/
                          rm $zipPath
                          Write-Host "Packer installed successfully."
                        }
                        else {
                          Write-Host "Packer already installed on Linux/macOS."
                        }
                      }

                # ✅ Verify Packer installation (Cross-platform)
                - task: PowerShell@2
                  displayName: "Verify Packer Installation (Cross-platform)"
                  inputs:
                    targetType: "inline"
                    script: |
                      Write-Host "Verifying Packer installation..."
                      if ($env:AGENT_OS -eq "Windows_NT") {
                        packer -v
                      }
                      else {
                        bash -c "packer version"
                      }

                # ✅ Replace Tokens (if applicable)
                - task: replacetokens@6
                  displayName: "Replace Tokens in Packer Variables"
                  inputs:
                    targetFiles: "${{ parameters.workingDirectory }}/variables/${{ parameters.imageName }}.pkrvars.hcl"
                    tokenPattern: "custom"
                    tokenPrefix: "__"
                    tokenSuffix: "__"
                    actionOnMissing: "warn"
                    keepToken: false

                # ✅ Initialize Packer backend with parameterized HCL file
                - script: |
                    packer init ${{ parameters.workingDirectory }}/${{ parameters.packerTemplateFile }}
                  displayName: "Packer Init"

                # ✅ Validate the Packer template with parameterized HCL file
                - script: |
                    cd ${{ parameters.workingDirectory }}
                    packer validate -var-file=variables/${{ parameters.imageName }}.pkrvars.hcl ${{ parameters.packerTemplateFile }}
                  displayName: "Packer Validate"