trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure/database/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-ci.yml  
  parameters:
    artifactName: "database-artifacts"
    team: "database"
    agentPool: "Lab"