trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure/devops/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-ci.yml  
  parameters:
    artifactName: "devops-artifacts"
    team: "devops"
    agentPool: "Lab"