trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure/networking/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-ci.yml  
  parameters:
    artifactName: "networking-artifacts"
    team: "networking"
    agentPool: "Lab"