trigger:
  branches:
    include:
      - main  
  paths:
    include:
      - azure/security/**  

pool:
  name: 'Lab'  

extends:
  template: templates/template-terraform-ci.yml  
  parameters:
    artifactName: "security-artifacts"
    team: "security"
    agentPool: "Lab"