#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - unzip
  - jq
  - git
  - python3
  - python3-pip
  - ansible

runcmd:
  - mkdir -p /etc/ansible/
  - echo "localhost" > /etc/ansible/hosts
  - systemctl restart sshd

final_message: "Cloud-init complete for build agent!"