subscription_id  = "__subscriptionid__" # Token replaced by pipeline
tenant_id        = "__tenantid__"       # Token replaced by pipeline
client_id        = "__clientid__"       # Token replaced by pipeline
client_secret    = "__clientsecret__"   # Token replaced by pipeline
resource_group   = "Compute"
location         = "eastus"
gallery_name     = "SharedImageGallary"
image_name       = "windows-2025-base"
windows_version  = "2025-Datacenter-smalldisk"